Upgrade tonic to v0.11
mechiru/google-api-proto pull request #20
Opened 2024-02-15 15:13 UTC by fenollp

And other (not super related nor important) things :)

2024-02-16 09:45 UTC, fenollp commented
@mechiru Ping just to make sure you'll be notified. 
I'm open to chat via email BTW if that can make our communication easier :)

2024-02-16 10:58 UTC, mechiru requested changes
@fenollp Thank you for your contribution!
Code change looks good.
Merge once you have corrected the tonic support version of the document.

2024-02-16 10:58 UTC, mechiru commented on README.md
> +| 1.512.0 <=       | 0.11.x | 0.11.x      |
```suggestion
| 1.515.0 <=       | 0.11.x | 0.11.x      |
```

2024-02-16 11:00 UTC, mechiru commented on README.md
> +| 1.512.0 <=       | 0.11.x | 0.11.x      |
If you are willing to modify it here, we will respond. Please mentions it to me.

2024-02-17 00:19 UTC, mechiru approved these changes
Thanks 😉

2024-02-17 00:20 UTC, merged

2024-02-20 17:27 UTC, fenollp commented
Ah it looks like `515` was pushed to crates.io https://crates.io/crates/google-api-proto/1.515.0/dependencies but
* this is the version point we pinned to use tonic `0.11` but it appears as requiring `0.10`
* the corresponding tag does not show on https://github.com/mechiru/google-api-proto/tags

Is your depoy pipeline broken? (and thanks for your time)