tonic 0.8 and prost 0.11 upgrade
mechiru/google-api-proto pull request #3
Opened 2022-09-12 00:23 UTC by shikhar

I was able to successfully run:

```
cargo xtask clean generate
```

2022-09-12 01:13 UTC, mechiru requested changes
@shikhar Thank you for your contribution.
Could you please fix just one document?

2022-09-12 01:13 UTC, mechiru commented on README.md
> +| 1.217.0 <=       | 0.8.x | 0.8.x       |
```suggestion
| 1.217.0 ≦        | 0.8.x | 0.8.x       |
```

2022-09-13 03:40 UTC, shikhar commented
@mechiru updated, but the version is a moving target because of the workflow, so may need fixing right before/after merge

2022-09-25 17:52 UTC, mechiru commented
Thank you! Sorry it took so long to check.

2022-09-25 17:52 UTC, merged